services:
  - type: web
    name: lingumate-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
